# https://anomalib.readthedocs.io/en/v2.2.0/markdown/guides/reference/models/image/patchcore.html
train_batch_size: 1
eval_batch_size: 1
max_epochs: 1 # Patchcore only needs 1 epoch
max_workers: 0
test_split_mode: "from_dir" # none, from_dir, synthetic, train_data
test_split_ratio: 0.2
val_split_mode: "same_as_test" # none, same_as_text, from_train, from_test, synthetic (from train_data)
val_split_ratio: 0.5 # not used if same_as_text
num_sanity_val_steps: 0 #(skip validation sanity checks)
gradient_clip_val: 0 #(no gradient clipping needed)
accelerator: "cpu"  # Also tried cpu, gpu, auto
inference_mode: False
n_parallel_jobs: 1

callbacks:
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      patience: 10
      monitor: pixel_val_AUROC
      mode: max

