# Model configuration
# https://anomalib.readthedocs.io/en/v2.2.0/markdown/guides/reference/models/image/dsr.html

model:
  class_path: "reverse_distillation" # For referencing in logs, saved models, etc.
  init_args:
    backbone: wide_resnet50_2                     # Backbone of CNN network. Defaults to "wide_resnet50_2". Other backbones are available; execute backbones.py
    layers: ["layer1", "layer2", "layer3"]        # Layers to extract features from the backbone CNN. Defaults to ["layer1", "layer2", "layer3"].
    anomaly_map_mode: "add"                       # Mode to generate anomaly map. add or multiply. Defaults to add.
    pre_trained: true                             # Boolean to check whether to use a pre_trained backbone. Defaults to True.
    pre_processor: true                           # Pre-processor for the model. Used to pre-process the input data before it is passed to the model. Defaults to None.
    post_processor: true                          # Post-processor for the model. Defaults to True.
    evaluator: true                               # Evaluator used to compute metrics. Defaults to True.
    visualizer: true  
    # Non-primitive types: reference other YAML files
    pre_processor: "configs/PreProcessor.yaml"  # or set to false to disable
    post_processor: "configs/PostProcessor.yaml"  # or set to false to disable
    evaluator: "configs/Evaluator.yaml"  # or set to false to disable
