# This is a product file that contains every information to inference a anomaly detection model for a irlbacher product
# like the MDF6
# Usually this is the result of a training run, after which a model can be used to detect anomalies
# This file mainly contains references to other setting files that are queried by the program that uses this file.

product: "cable"

logging:
  logFileName: "general.log"

model:
  name: "InpFormer"
  config: InpFormer.yaml
  weights_path: "results/MVTecAD/cable/inp_former/tiled/checkpoints"
  trainingDir: "../results/MVTecAD/cable/inp_former/tiled"

tiling:
  enable: True
  config: "TiledEnsemble.yaml"

trainer:
  config: "Training_InpFormer.yaml"

inferencer:
  config: "Prediction.yaml"

dataset:
  name: "MVTecADShort"
  category: "cable"
  split:
    - "train"
    - "test"